# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-05 03:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divisas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monedero',
            name='monto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=11),
        ),
    ]
